### ISSUE TITLE
Getting a "_LinAlgError: cholesky" error

### ISSUE THREAD

**Issue by previtus** [markusfoote/mag1c#2]
Dear Markus Foote,
I have a question in regards of running code from this repository on the AVIRIS-NG data (namely one swath of data from [here (10GB)](https://avng.jpl.nasa.gov/avng/y19_data/ang20190922t192642.tar.gz) ).

After running:
`!mag1c --gpu "ang20190922t192642_rdn_v2x1/ang20190922t192642_rdn_v2x1_img" --out "test_out"`

I receive the following error (with never versions of torch):
`  File "/usr/local/lib/python3.7/dist-packages/mag1c/mag1c.py", line 124, in acrwl1mf
    Cit = torch.cholesky_solve(torch.transpose(target, 1, 2), torch.cholesky(C, upper=False), upper=False)
torch._C._LinAlgError: cholesky: (Batch element 0): The factorization could not be completed because the input is not positive-definite (the leading minor of order 9 is not positive-definite).
`
And with older versions of torch (namely the suggested 1.3.1) this error:
`  File "mag1c.py", line 124, in acrwl1mf
    Cit = torch.cholesky_solve(torch.transpose(target, 1, 2), torch.cholesky(C, upper=False), upper=False)
RuntimeError: cholesky_cuda: For batch 0: U(8,8) is zero, singular U. 
`

An output file with 5 bands is produced, but the 4th and 5th bands (corresponding to "Matched Filter Results" and "Albedo Factor") seem to be empty (full of -9999.0).

Am I missing some specific parameters I should set? Should I use some special "target spectrum" as input for the data? Or have I just been unlucky with the selection of the file I am testing this code with :)?

Thank you for any help or comments,
Vit Ruzicka

_PS: I also tried this on one other file and with or without the gpu support, the error stays the same_

**Comment by previtus** [comment]
Fixed this, I had to add the "--geo" file to the call.

**Comment by CGrookie** [comment]
> Fixed this, I had to add the "--geo" file to the call.
Hello, could you provide your data and commands? I would like to test this program
